= COMP3670

== Tutorials

* http://www.w3schools.com/[w3schools]

== HTML5

* http://diveintohtml5.info/[Dive into HTML5]
* https://html.spec.whatwg.org/multipage/[HTML5 specification]
* https://github.com/diegocard/awesome-html5[Awesome HTML5]
* http://getbootstrap.com/getting-started/#download[Bootstrap]
* https://github.com/ironsummitmedia/startbootstrap/[Bootstrap themes]
* http://semantic-ui.com/[Semantic-UI]
* https://validator.w3.org/[Validator]

== JavaScript

[cols="3"]
|===
|Awesome libraries
|https://github.com/sorrycc/awesome-javascript[Client-side]
|https://github.com/sindresorhus/awesome-nodejs[Server-side]

|Multimedia
|https://pixlcore.com/read/WebcamJS[Webcam.js]
|http://mediaelementjs.com/[Play video and audio]

|Presentations
|http://impress.github.io/impress.js/#/bored[Impress.js]
|https://github.com/hakimel/reveal.js[Reveal.js]

|Drawing
|http://d3js.org/[D3]
|http://threejs.org/[Three.js]

|Packaging
|https://cordova.apache.org/[Cordova (phone)]
|http://electron.atom.io/[Electron (desktop)]

|https://html5test.com/[Feature detection]
|https://modernizr.com/docs[Modernizr]
|http://caniuse.com/[Browser support]

|Polyfills/fallbacks
|https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-browser-Polyfills[Polyfills/fallbacks]
|http://html5please.com/[Guide]

|===

== CSS

* https://github.com/sotayamashita/awesome-css[Awesome CSS stuff]
* https://fortawesome.github.io/Font-Awesome/icons/[Font awesome icons]
* http://daneden.github.io/animate.css/[Animate.css]
* http://necolas.github.io/normalize.css/[Normalize.css]
* http://lesscss.org/features/[Less]

== Random

* http://www.wonder-tonic.com/geocitiesizer/[Geocities-izer]
* http://needsmorejpeg.com/[Don't use JPEG inappropriately]
* http://media.tojicode.com/q3bsp/[Quake in WebGL]
* http://www.stilldrinking.org/programming-sucks[Programming sucks]

== Some backend frameworks

[cols="3"]
|===
|*JavaScript*
|https://nodejs.org/en/[Node.js]
|http://expressjs.com/[Express.js]

|*C#*
|http://www.asp.net/[ASP.NET]
|

|*Java*
|https://www.playframework.com/[Play]
|http://sparkjava.com/[Spark]

|*Python*
|https://www.djangoproject.com/[Django]
|http://flask.pocoo.org/[Flask]

|*Ruby*
|http://rubyonrails.org/[Ruby Rails]
|http://www.sinatrarb.com/[Sinatra]

|*PHP*
|https://laravel.com/[Laravel]
|http://cakephp.org/[Cake]

|===

== January 6

=== Introduce yourself
Welcome! Let's get to know each other with an icebreaker. Answer these questions:

* What is your name?
* What is your major and why did you pick it?
* Tell us something nobody else in the room knows about you.

== January 8

=== Install Git
Download and install git for your platform.

[cols="1a,2a"]
|===
|*Download*
|*Installation Notes*

|https://git-scm.com/download/win[Git for Windows]
|Stick with the default options and click `Next` until finished.

|http://git-scm.com/download/mac[Git for Mac OS X]
|Got an error? Try:

* Apple menu -> System Preferences... -> Security & Privacy -> Open Anyway.
* Otherwise, try: Applications -> Utilities -> Terminal and type `git` and follow instructions to install git.

|http://git-scm.com/download/linux[Git for Linux]
|Use `sudo` with your package manager.

|===

=== Run starterupper

Starterupper configures git for this class.
It is safe to run if you already use git.

Copy/paste the entire command below...

----
curl https://raw.githubusercontent.com/lawrancej/COMP3670-2016/master/main.sh | bash
----

...into your terminal:

[cols="1a,1a,1a,1a"]
|===
|*Plaform*
|*Terminal*
|*Copy shortcut*
|*Paste shortcut*

|*Windows*
|Windows key -> Git Bash
|`Ctrl-C`
|`Shift-Insert`

|*Mac*
|Applications -> Utilities -> Terminal
|`Command-C`
|`Command-V`
|===

== January 11

Install https://atom.io/[Atom]

Let's dive into HTML, CSS, JavaScript.

== January 12

. Write a home page
. Write down project ideas (look around at existing web applications)
. Begin to think about who to work with

----
git checkout -b gh-pages
git push origin gh-pages
----

Go to: http://lawrancej.github.io/COMP3670-2016/Code/example.html

== January 13

* https://nodejs.org/en/download/stable/[Install Node.js] Stable (not LTS) for your platform.
* Also, https://www.docker.com/docker-toolbox[Instal Docker toolbox] for your platform.
* https://fortawesome.github.io/Font-Awesome/get-started/[Font awesome]

----
cd ~/COMP3670-2016
git pull upstream master
cd Code
node node-example.js
----

Go to: http://127.0.0.1:1337/ and it should say `Hello World`

== January 15



In Atom, go to Preferences... -> Install or File -> Settings.. -> Install

Install these packages:

* `linter-eslint`
* `jshint`
* `linter-csslint`
* `linter-htmlhint`
* `atom-html-preview`
* `color-picker`
* `merge-conflicts`

`npm` is node.js' package manager (hence the name).
You can create packages (i.e., your web app) using `npm init`.

Some packages are meant for global installation, like http://browserify.org/[`browserify`] and https://mochajs.org/[`mocha`].

----
npm install -g browserify
npm install -g mocha
----

[NOTE]
====
Did you see any errors? If so, do this and try the command above again:
----
sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
----
====

Other packages only make sense as a dependency for your own package, like `express` (web framework).

----
cd ~/COMP3670-2016
mkdir -p Code/example-app
cd Code/example-app
npm init
echo "node_modules" >> .gitignore
npm install express --save
npm install express-handlebars --save
touch index.js
----

Go here and copy paste: http://expressjs.com/en/starter/hello-world.html[Hello world in express] into `index.js`.

----
node index.js
----

Go to http://localhost:3000/[this page].

Now, let's serve static files.

----
mkdir public
touch public/index.html
----

Fill `public/index.html` with something sensible.

Add this line to `index.js` (after `var app = express();`) and save:

----
// serve up any request to /static using files from public
app.use('/static', express.static('public'));
----

Next, run this command

----
node index.js
----

Then, go to http://localhost:3000/static[this page], served statically.

== January 19

Copy paste this http://getbootstrap.com/getting-started/[Bootstrap] stuff into your html's `head`

----
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
----

Also, see: http://semantic-ui.com/[Semantic UI]

Let's add http://handlebarsjs.com/[handlebars] to express, as done here: https://github.com/ericf/express-handlebars[Express-handlebars]
Or a https://www.youtube.com/watch?v=m5ribwPpIPw[youtube video illustrating something similar]

Other topics:

* http://www.w3schools.com/html/html_entities.asp[HTML entities]
* Double vs. triple stash (double escapes html, triple does not)
* http://json.org/example.html[JSON]

If you want to see my express code, do this:

----
cd ~/COMP3670-2016
git fetch --all
# merge latest from master
git merge upstream/master
# look at my code
git checkout upstream/express-example
git checkout -b express-example
# go back to the master branch
git checkout master
----

== January 20

Input from forms into the backend.

* HTML forms
* HTTP methods, requests, responses
* URL encodings
