= COMP3670

https://github.com/lawrancej/web-example

== Preliminaries

. https://github.com/lawrancej/COMP3670-2016/blob/master/Setup.adoc[Setup all software]
. https://github.com/lawrancej/COMP3670-2016/blob/master/Resources.adoc[Peruse relevant resources]
. https://github.com/lawrancej/COMP3670-2016/blob/master/Git.adoc[How to use Git]
. https://education.github.com/pack/join[Get the Github Student Developer Pack]
. https://education.github.com/pack[Then, go here].

== Useful packages

[horizontal]
For...:: `npm install ___ --save`
PostgreSQL database:: https://www.npmjs.com/package/pg[pg]
SQLite database:: https://www.npmjs.com/package/sqlite3[sqlite3]
File uploads:: https://www.npmjs.com/package/formidable[formidable]
POST requests:: https://www.npmjs.com/package/body-parser[body-parser]
HTTPS:: https://www.npmjs.com/package/letsencrypt[letsencrypt]
Authentication:: https://www.npmjs.com/package/passport[passport]
Asset bundling:: https://www.npmjs.com/package/broccoli[Broccoli]

== Agenda

[horizontal]
January 6:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[Introduce yourself, About this course]
January 8:: https://github.com/lawrancej/COMP3670-2016/blob/master/Setup.adoc[Setup all software] and https://github.com/lawrancej/COMP3670-2016/blob/master/Git.adoc[git]
January 11:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[Introduction to HTML, CSS, JavaScript, and image formats]
January 12:: https://github.com/lawrancej/COMP3670-2016/blob/master/Labs.adoc[Lab 1: Home page]
January 13:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[Introduction to Node.js]
January 15:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[Introduction to npm, Express.js]
January 19:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[Introduction to Bootstrap, Handlebars]
January 20:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[Introduction to Forms (GET)]
January 22:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[Introduction to Forms (POST)]
January 25:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[Speed dating / CSS]
January 26:: https://github.com/lawrancej/COMP3670-2016/blob/master/Labs.adoc[Lab 2: Mad Libs]
January 27:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[Databases]
January 29:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[More about databases]
February 1:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[Passport and authentication]
February 2:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[React, browserify]
February 3:: https://github.com/lawrancej/COMP3670-2016/blob/master/Labs.adoc[Lab 3: Low-fidelity Prototype]
February 5:: Class canceled
February 8:: Class canceled
February 9:: https://github.com/lawrancej/COMP3670-2016/blob/master/Labs.adoc[Finish Lab 3: Low-fidelity Prototype]
February 16:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[AJAX and JQuery]
February 19:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[Heroku stuff]
February 22:: https://github.com/lawrancej/COMP3670-2016/blob/master/Lectures.adoc[Hosting and domains]
February 23:: Front-end prototype demo
February 24:: http://mozilla.github.io/localForage/[Local storage] and http://lawrancej.github.io/COMP3670-2016/location.html[location] and https://github.com/nodemailer/nodemailer[emailing]
February 29:: http://www.w3schools.com/cssref/tryit.asp?filename=trycss3_media_example1[CSS Media Queries], https://modernizr.com/docs[Detect JavaScript], Database stuff
March 1:: More information about local testing with databases
March 2:: https://drownattack.com/[DROWN attack], http://www.thedailywtf.com/articles/bidding-on-security[JSF**k], and http://blog.checkpoint.com/2016/02/02/ebay-platform-exposed-to-severe-vulnerability/[Ebay vulnerability]
March 4:: http://www.jsfuck.com/[JSF**k], http://promises-aplus.github.io/promises-spec/[Promises], https://www.youtube.com/watch?v=b0EF0VTs9Dc[Monads and promises]
March 22:: Milestone 2
April 5:: Milestone 3
Final presentation:: Yay! DONE!

== TODO (not now, just notes to self)

* shared database connection
* hosting
* custom tags
* https
* cross origin resource sharing / same origin policy
* promises
* mocha testing

https://education.github.com/pack[Github student pack]
https://www.heroku.com/pricing[Heroku free hosting]

----
docker-machine ssh default
----

So, you can mount files or directories on OS X using.

----
docker run -v /Users/<path>:/<container path> ...
----

For example:

----
docker run -v /Users/lawrancej/COMP3670-2016:/webdev -i -t centos /bin/bash
----

On Windows, mount directories using:

----
docker run -v /c/Users/<path>:/<container path> ...`
----

All other paths come from your virtual machine’s filesystem.
