= COMP3670

== Preliminaries

. https://github.com/lawrancej/COMP3670-2016/blob/master/Setup.adoc[Setup all software]
. https://github.com/lawrancej/COMP3670-2016/blob/master/Resources.adoc[Peruse relevant resources]

== January 6

=== Introduce yourself
Welcome! Let's get to know each other with an icebreaker. Answer these questions:

* What is your name?
* What is your major and why did you pick it?
* Tell us something nobody else in the room knows about you.

== January 8

Starterupper configures git for this class.
It is safe to run if you already use git.

Copy/paste the entire command below...

----
curl https://raw.githubusercontent.com/lawrancej/COMP3670-2016/master/main.sh | bash
----

...into your terminal:

[cols="1a,1a,1a,1a"]
|===
|*Plaform*
|*Terminal*
|*Copy shortcut*
|*Paste shortcut*

|*Windows*
|Windows key -> Git Bash
|`Ctrl-C`
|`Shift-Insert`

|*Mac*
|Applications -> Utilities -> Terminal
|`Command-C`
|`Command-V`
|===

== January 11

Let's dive into HTML, CSS, JavaScript.

== January 12

. Write a home page
. Write down project ideas (look around at existing web applications)
. Begin to think about who to work with

Github can serve files in your repo under the `gh-pages` branch.

----
# create the gh-pages branch
git checkout -b gh-pages
# push the gh-pages branch to github
git push origin gh-pages
----

Once there, any html in that branch will be accessible via your-user-name.github.io.

For example, go to: http://lawrancej.github.io/COMP3670-2016/Code/example.html

== January 13

https://fortawesome.github.io/Font-Awesome/get-started/[Font awesome] is a collection of useful icons.

To test that node is working correctly, do the following in the command line:
----
cd ~/COMP3670-2016
git pull upstream master
cd Code
node node-example.js
----

Go to: http://127.0.0.1:1337/ and it should say `Hello World`

== January 15

`npm` is node.js' package manager (hence the name).
You can create packages (i.e., your web app) using `npm init`.

Some packages are meant for global installation, like http://browserify.org/[`browserify`] and https://mochajs.org/[`mocha`], installed earlier.

Other packages only make sense as a dependency for your own package, like `express`, a web framework for node.js.

Type these commands, but don't copy/paste, because `npm init` is interactive.

----
cd ~/COMP3670-2016
mkdir -p Code/example-app
cd Code/example-app
npm init
echo "node_modules" >> .gitignore
npm install express --save
npm install express-handlebars --save
touch index.js
----

Go here and copy paste: http://expressjs.com/en/starter/hello-world.html[Hello world in express] into `index.js`.

Then, in the command line, run it.

----
node index.js
----

To see that it works, go to http://localhost:3000/

Now, let's serve static files.

----
mkdir public
touch public/index.html
----

Fill `public/index.html` with something sensible.

Add this line to `index.js` (after `var app = express();`) and save:

----
// serve up any request to /static using files from public
app.use('/static', express.static('public'));
----

Next, stop `node` with `Ctrl-C` and re-run it:

----
node index.js
----

Then, go to http://localhost:3000/static

That page is served statically.

== January 19

http://getbootstrap.com/getting-started/[Bootstrap] is a popular front-end framework.
It has a grid system (for layouts that respond to screen size),
as well as nice default styles for things like navigation bars and alerts.

Copy this HTML into your html's `head`

----
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
----

http://semantic-ui.com/[Semantic UI] is similar to bootstrap, but has additional styling.

http://handlebarsjs.com/[Handlebars] is a template system, enabling separation of html (view) from code (model).
Handlebars replaces placeholders in a file with data from a http://json.org/example.html[JavaScript object (JSON)]
Placeholders come in two varieties; double-stash `{{placeholder}}` or triple-stash `{{{placeholder}}}`
Handlebars escapes HTML into http://www.w3schools.com/html/html_entities.asp[HTML entities] for double-stash placeholders, but not for triple-stash placeholders.

Let's https://github.com/ericf/express-handlebars[add handlebars to express], as https://www.youtube.com/watch?v=m5ribwPpIPw[demonstrated on youtube]

If you want to see my express code, do this:

----
cd ~/COMP3670-2016
git fetch --all
# merge latest from master
git merge upstream/master
# look at my code
git checkout upstream/express-example
# create a local branch that tracks upstream
git checkout -b express-example
# Get updates to express-example
git pull upstream express-example
# go back to the master branch
git checkout master
----

== January 20

Input from forms into the backend.

URL: Uniform Resource Locator (paths for the web)

Absolute URLs:

----
scheme://domain/path/to/something?key=value&anotherKey=anotherValue
scheme://domain/path/to/something#fragment
----

Relative URLs:
Suppose we are at `http://localhost:3000/some/place.html`

----
/another-place
# the absolute URL is http://localhost:3000/another-place
another-place
# the absolute URL is http://localhost:3000/some/another-place
../some-place-secret
# the absolute URL is http://localhost:3000/some-place-secret
----

action is where we send form data to (that's a URL)
method is how we send data to our "action"
URL

* HTML forms
* HTTP methods, requests, responses
* URL encodings

== TODO (not now, just notes to self)

----
docker-machine ssh default
----

So, you can mount files or directories on OS X using.

----
docker run -v /Users/<path>:/<container path> ...
----

For example:

----
docker run -v /Users/lawrancej/COMP3670-2016:/webdev -i -t centos /bin/bash
----

On Windows, mount directories using:

----
docker run -v /c/Users/<path>:/<container path> ...`
----

All other paths come from your virtual machine’s filesystem.
